import React from "react";

import avatar1 from "assets/img/avatar-1.jpg";
import image3 from "assets/img/3.jpg";
import image4 from "assets/img/4.jpg";
import iconChecked from "assets/svg/icon-checked.svg";

const SectionAbout = ({ chooseyourcoachScroll, refProp }) => {
  return (
    <section ref={refProp} id="about" className="about spacer-double-lg">
      <div className="container">
        <div className="row align-items-center justify-content-around">
          <div className="col-lg-5 col-md-9 order-2">
            <h3 className="h1">Actualice su negocio y cambie su vida</h3>
            <p className="lead">
              Nuestro trabajo con los clientes siempre ha estado en la
              intersección de profunda experiencia en la industria y amplias
              capacidades.
            </p>
            <div className="max-width-2">
              <hr className="my-5" />
            </div>
            <div className="media bg-secondary p-3 rounded">
              <img
                className="avatar-sm rounded-circle mr-3"
                src={avatar1}
                alt="avatar1"
                srcSet={avatar1}
              />
              <div className="media-body">
                <h4 className="h6 mb-0">Melissa Wagner</h4>
                <p className="text-muted mb-0">
                  "Felicitaciones Team Foxconf, no podríamos haberlo hecho. sin
                  el esfuerzo de todos ".
                </p>
              </div>
            </div>
          </div>
          <div className="col-lg-5 col-md-9 order-1 mb-5 mb-lg-0">
            <img
              src={image3}
              alt="image3"
              srcSet={image3}
              className="img-fluid rounded shadow-lg z-index-2 position-relative"
            />
            <div className="position-absolute p-0 col-4 col-xl-4 top left mt-5 mn-lg-l mn-sm-l d-none d-md-block">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                x="0px"
                y="0px"
                viewBox="0 0 219.0727 218.875"
                enableBackground="new 0 0 219.0727 218.875"
                xmlSpace="preserve"
              >
                <g>
                  <g>
                    <rect fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="17.9375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="35.8125" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="53.9375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x={73} fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="90.7602" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="109.0102"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="15.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="34.5745" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="52.6618" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="71.5025" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="90.3431" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="17.9375"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="125.375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="143.625" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="161.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="177.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="196.375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="214.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                </g>
              </svg>
            </div>
          </div>
        </div>
        <div className="row align-items-center justify-content-around spacer-one-top-lg mb-6 pb-6">
          <div className="col-lg-5 col-md-9 order-1">
            <h3 className="h1">
              En Demo-Coaching hacemos las cosas de manera diferente
            </h3>
            <p className="lead">
              Nuestro trabajo con los clientes siempre ha estado en la
              intersección de profunda experiencia en la industria y amplias
              capacidades.
            </p>
            <div className="row">
              <div className="col-md-6">
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #1</div>
                </div>
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #2</div>
                </div>
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">
                    Item #3
                    <span className="badge badge-secondary badge-pill ml-1">
                      <span>Nuevo</span>
                    </span>
                  </div>
                </div>
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #4</div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #5</div>
                </div>
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #6</div>
                </div>
                <div className="media align-items-center mb-1">
                  <img
                    className="mr-2 icon-check"
                    src={iconChecked}
                    alt="iconChecked"
                    srcSet={iconChecked}
                  />
                  <div className="media-body h6">Item #7</div>
                </div>
              </div>
            </div>
            <a
              className="scroll btn btn-primary btn-radius-bottom-left mt-5 mb-lg-0 mb-5"
              href="#choose-your-coach"
              onClick={chooseyourcoachScroll}
            >
              <span className="mn-top">Elige tu Coach</span>
            </a>
          </div>
          <div className="col-lg-5 col-md-9 order-2">
            <img
              src={image4}
              alt="image4"
              srcSet={image4}
              className="img-fluid rounded shadow-lg z-index-2 position-relative"
            />
            <div className="position-absolute p-0 col-4 col-xl-4 top right mt-5 mn-lg-r mn-sm-r d-none d-md-block">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                x="0px"
                y="0px"
                viewBox="0 0 219.0727 218.875"
                enableBackground="new 0 0 219.0727 218.875"
                xmlSpace="preserve"
              >
                <g>
                  <g>
                    <rect fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="17.9375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="35.8125" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="53.9375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect x={73} fill="#E7EAF3" width="4.125" height={4} />
                    <rect x="90.7602" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="109.0102"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="15.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="15.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="34.5745" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="34.5745"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="52.6618" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="52.6618"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="71.5025" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="71.5025"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="90.3431" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="90.3431"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="17.9375"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="109.1838"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="125.375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="125.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="143.625" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="143.625"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="161.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="161.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="177.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="177.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="196.375" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="196.375"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                  <g>
                    <rect y="214.875" fill="#E7EAF3" width="4.125" height={4} />
                    <rect
                      x="17.9375"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="35.8125"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="53.9375"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x={73}
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="90.7602"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="109.0102"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="126.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="144.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="162.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="181.0102"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="198.8852"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                    <rect
                      x="214.9477"
                      y="214.875"
                      fill="#E7EAF3"
                      width="4.125"
                      height={4}
                    />
                  </g>
                </g>
              </svg>
            </div>
          </div>
        </div>
        <div className="row justify-content-center">
          <div className="col-auto">
            <ul className="radius-bottom-right px-5 pt-2 pb-2 list-unstyled rounded text-center d-flex mb-0 bg-primary-2 flex-wrap justify-content-center">
              <li className="my-5 mx-5 mx-lg-5">
                <div className="h1 text-white mb-2">80%</div>
                <h6 className="mb-0 text-light">Casos terminados</h6>
              </li>
              <li className="my-5 mx-5 mx-lg-5">
                <div className="h1 text-white mb-2">1.5k</div>
                <h6 className="mb-0 text-light">Clientes felices</h6>
              </li>
              <li className="my-5 mx-5 mx-lg-5">
                <div className="h1 text-white mb-2">45</div>
                <h6 className="mb-0 text-light">Premios ganadores</h6>
              </li>
              <li className="my-5 mx-5 mx-lg-5">
                <div className="h1 text-white mb-2">12+</div>
                <h6 className="mb-0 text-light">Oficinas</h6>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
};

export { SectionAbout };
